---
title: "Juan's Modeling - RF"
author: "Juan Gonzalez"
date: "2025-12-04"
output: html_document
---

# Loading the Data and Packages

```{r, warning=FALSE, message=FALSE}

packages <- c("lubridate", "tidyverse", "tidymodels", "rpart.plot", "vip", "Metrics", "randomForest")

for (pkg in packages) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
    library(pkg, character.only = TRUE)
  }
}
remove(packages, pkg)

df_load <- read.csv("~/Documents/GitHub/project-5/CSV Files/merged_data.csv")

df <- df_load %>% select(-id, -last_name, -name, -life_sentence, -death_sentence)%>%
  mutate(time_sentenced_prior = round(time_sentenced_prior,2),
         height = as.numeric(height),
         weight = as.numeric(weight)) %>% filter(!hair %in% c("Sandy", "Not Available"),
                                                 !eyes %in% c("Not Available"),
                                                 current_sentence > 0)

df <- na.omit(df)

df <- df |>
  mutate(across(where(is.character), as.factor),
         across(where(is.logical), ~factor(., levels = c(FALSE, TRUE))))


```


# Preparing training and test data split

```{r}

set.seed(445)

#df <- df %>% slice_sample(n = 3000)

df_split <- initial_split(df, prop = 0.7)

df_train <- training(df_split)
df_test <- testing(df_split)


#rf



rf_spec <- rand_forest(mtry = sqrt(.cols())) |>
  set_engine("randomForest", importance = TRUE) |>
  set_mode("regression")

start <-Sys.time()

rf_fit <- rf_spec |>
  fit(current_sentence ~ ., data = df_train)

end <-  Sys.time()

end - start

# For saving fit results
#saveRDS(rf_fit, "RFfit_model_juan.rds")


#Load the model
#rf_fit <- readRDS("rf_fit_model.rds")


vip(rf_fit)


augmented <- augment(rf_fit, new_data = df_test) %>% pull(.pred)


rmse(df_test$current_sentence, augmented)


#bagging
# bagging_spec <- rand_forest(mtry = .cols()) |>
#   set_engine("randomForest", importance = TRUE) |>
#   set_mode("regression")
# 
# bagging_fit <- bagging_spec |>
#   fit(high_sales ~ ., data = df_train)



```


```{r, message = FALSE}

#OOB RMSE
rf_engine <- rf_fit |> extract_fit_engine()
sqrt(rf_engine$mse[rf_engine$ntree])


try <- test %>% mutate(current_sentence_rnd = round(current_sentence,0)) %>% 
  group_by(current_sentence_rnd) %>% summarise(obs = n(), rmse = mean(abs(current_sentence_rnd - prediction)))

ggplot(data = try, aes(x = current_sentence_rnd, y = rmse)) + 
  labs(title = "RMSE by Sentence Length", x = "Sentencing Time", y = "RMSE") +
  geom_smooth(method = "loess", se = FALSE, color = "coral4") + geom_line() +theme_bw()





#For entire dataset
df_with_preds <- df %>%
  mutate(prediction = predict(rf_fit, new_data = df)$.pred)


rmse_alldata <- df_with_preds %>% mutate(current_sentence_rnd = round(current_sentence,0)) %>% 
  filter(current_sentence_rnd >0) %>% 
  group_by(current_sentence_rnd) %>% summarise(obs = n(), rmse = mean(abs(current_sentence_rnd - prediction)))


ggplot(data = rmse_alldata, aes(x = current_sentence_rnd, y = rmse)) + 
  labs(title = "RMSE by Sentence Length", x = "Sentencing Time", y = "RMSE") +
  geom_smooth(method = "loess", se = FALSE, color = "coral4") + geom_line() +theme_bw()


write.csv(rmse_alldata, "RF_RMSEbySentencing.csv", row.names = FALSE)


```









